hydra:
  run:
    dir: data/raw/poisson1d/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

problem:
  test_function: rosenbrock
  dim: 128
  num_samples: 100
  num_iter: 50000
  initial_range:
    - -1
    - 1
  tensor_type: torch.cuda.DoubleTensor

solver:
  _target_: __main__.TestFunctionSolver
  problem: ${problem}

surrogate:
  _target_: nigbms.modules.surrogates.SurrogateSolverMLP
  params_fix: None
  params_learn: 
    x:
      - ${problem.dim}
  features:
  model:

wrapper:
  grad_type: cv_fwd
  jvp_type: forwardFD
  # jvp_type: forwardAD
  jvp_type_s: forwardAD
  Nv: 1
  eps: 1.0e-08
  update_steps: 0
  output_type: loss
  v_scale: 1.0
optimizer:
  m_opt:
    _target_: torch.optim.Adam
    lr: 0.01
  s_opt:
    _target_: torch.optim.Adam
    lr: 0.01
  m_clip: null
  s_clip: null
loss:
  'y': 0
  dvf: 1.0
seed: 0
log_gradient: true
