hydra:
  run:
    dir: outputs/minimize_testfunctions/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

problem:
  test_function: sphere
  dim: 128
  num_samples: 100
  num_iter: 1000
  initial_range:
    - -1
    - 1
  tensor_type: torch.cuda.DoubleTensor

solver:
  _target_: nigbms.modules.solvers.TestFunctionSolver
  params_fix: 
    test_function: ${problem.test_function}
  params_learn: 
    x:
      - ${problem.dim}

surrogate:
  _target_: nigbms.modules.surrogates.SurrogateSolver
  params_fix: ${solver.params_fix}
  params_learn: ${solver.params_learn}
  features: ${surrogate.params_learn}
  model:
    _target_: nigbms.modules.models.MLP
    in_dim: ${calc_in_dim:${surrogate.features}}
    out_dim: 1
    num_layers: 1
    num_neurons: 4096
    hidden_activation: nn.GELU
    output_activation: nn.Identity
    batch_normalization: False
    weight_scale: 0.1
  # model:
  #   _target_: nigbms.modules.models.CNN1D
  #   in_channels: ${calc_in_channels:${surrogate.features}}
  #   out_unit: 1
  #   base_channels: 64
  #   kernel_size: 1
  #   batch_normalization: False
  #   hidden_activation: nn.GELU
  #   output_activation: nn.Identity
  #   num_conv_layers: 2
  #   num_fcn_layers: 2
    

wrapper:
  grad_type: cv_fwd
  jvp_type: forwardAD
  eps: 0
  Nv: 1
  v_scale: 1.0
  v_dist: rademacher

loss:
  s_loss:
    _target_: nigbms.modules.losses.SurrogateSolverLoss
    weights:
      dvf_loss: 1
      dvf_loss_relative: 0
      y_loss: 0

optimizer:
  m_opt:
    _target_: torch.optim.SGD
    lr: 0.01
  s_opt:
    _target_: torch.optim.SGD
    lr: 0.001
    momentum: 0.9
  m_clip: null
  s_clip: 100.0

wandb: 
  project: minimize_testfunctions
  mode: online
seed: 0