hydra:
  run:
    dir: data/outputs/minimize_testfunctions/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True

problem:
  test_function: sphere
  dim: 128
  num_samples: 100
  num_iter: 2000
  initial_range:
    - -1
    - 1
  tensor_type: torch.cuda.DoubleTensor

solver:
  _target_: nigbms.modules.solvers.TestFunctionSolver
  params_fix: 
    test_function: ${problem.test_function}
  params_learn: 
    x:
      - ${problem.dim}

surrogate:
  _target_: nigbms.modules.surrogates.SurrogateSolverMLP
  params_fix: {}
  params_learn: 
    x:
      - ${problem.dim}
  features: ${surrogate.params_learn}
  model:
    _target_: nigbms.modules.models.MLP
    layers:
      - ${calc_indim:${surrogate.features}}
      - 128
      - 128
      - 1
    hidden_activation: nn.GELU
    output_activation: nn.Identity
    batch_normalization: False

wrapper:
  grad_type: cv_fwd
  jvp_type: forwardAD
  Nv: 1
  eps: 1.0e-08
  update_steps: 0
  v_scale: 1.0

loss:
  s_loss:
    _target_: nigbms.modules.losses.SurrogateSolverLoss
    weights:
      dvf_loss: 1

optimizer:
  m_opt:
    _target_: torch.optim.Adam
    lr: 0.01
  s_opt:
    _target_: torch.optim.Adam
    lr: 0.01
  m_clip: null
  s_clip: null

seed: 0
