project: minimize_testfunctions
program: nigbms/train/minimize_testfunctions.py
metric:
  name: ymean
method: grid
parameters:
  optimizer.m_opt.lr:
    values:
      - 0.1
      - 0.01
      - 0.001

# for hydra compatibility
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}