offline_dataset:
  _target_: nigbms.modules.data.OfflineDataset
  data_dir: /workspaces/nigbms/data/raw/poisson1d/2024-08-12_12-53-14
  meta_df: null
  rtol_dist:
    _target_: nigbms.utils.distributions.NumpyConstant
    shape: null
    val: 1.0e-6
  maxiter_dist:
    _target_: nigbms.utils.distributions.NumpyConstant
    shape: null
    val: 1000
  data_format: pt
  is_A_fixed: True