offline_dataset:
  _target_: nigbms.modules.data.OfflineDataset
  data_dir: /workspaces/nigbms/data/raw/poisson1d/sample
  meta_df: null
  rtol_dist:
    _target_: nigbms.utils.distributions.NumpyConstant
    shape: null
    val: 1.0e-6
  maxiter_dist:
    _target_: nigbms.utils.distributions.NumpyConstant
    shape: null
    val: 1000
  data_format: pt
  is_A_fixed: True

online_dataset:
  _target_: nigbms.modules.data.OnlineDataset
  task_params_class: nigbms.data.generate_poisson2d.Poisson2DParams
  task_constructor: nigbms.data.generate_poisson2d.construct_petsc_poisson2d_task
  distributions:
    coef:
      _target_: nigbms.utils.distributions.NumpyNormal
      shape: [2,]
      mean: 0
      std: 1
    N:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      val: 10
    degree:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      val: 1
    rtol:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      val: 1.0e-6
    maxiter:
      _target_: nigbms.utils.distributions.NumpyConstant
      shape: null
      val: 1000

offline_datamodule:
  _target_: nigbms.modules.data.OfflineDataModule
  data_dir: ${offline_dataset.data_dir}
  dataset_sizes: 
    train: 100
    val: 100
    test: 100
  rtol_dists:
    train: ${offline_dataset.rtol_dist}
    val: ${offline_dataset.rtol_dist}
    test: ${offline_dataset.rtol_dist}
  maxiter_dists:
    train: ${offline_dataset.maxiter_dist}
    val: ${offline_dataset.maxiter_dist}
    test: ${offline_dataset.maxiter_dist}
  is_A_fixed: ${offline_dataset.is_A_fixed}
  data_format: ${offline_dataset.data_format}
  batch_size: 32
  num_workers: 0