petsc_cg:
  _target_: nigbms.modules.solvers.PETScKSP
  params_fix:
    history_length: 100
    # ksp
    ksp_type: cg
    ksp_divtol: 1.0e+10
    ksp_norm_type: unpreconditioned
    # pc
    pc_type: none
  params_learn: {}
  debug: False


