site_name: Non-intrusive Gradient-based Meta-solving
# 
site_author: Sohei Arisaka
# 
theme: material
plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    default_handler: python 

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Code Reference: reference/