project: minimize_testfunctions
program: nigbms/train/minimize_testfunctions.py
name: adam
metric:
  name: cos_sim
method: grid
parameters:
  problem.dim:
    values:
      - 32
      - 128
      - 512
  wrapper.grad_type: 
    values:
      - f_true
      - f_fwd
      - f_hat_true
      - cv_fwd
  wrapper.Nv:
    values:
      - 1
      - 4
      - 16

# for hydra compatibility
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}